title: EEF Security WG
description: Documentation, specifications and code from the Security Working Group of the Erlang Ecosystem Foundation
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme