title: EEF Security WG
description: Documentation, specifications and code from the Security Working Group of the Erlang Ecosystem Foundation
remote_theme: erlef/eef-jekyll-theme@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap
defaults:
- scope:
    path: "aegis/roadmap"
  values:
    layout: "milestone"
    is_aegis_milestone: true
collections:
  articles:
    output: false
    sort_by: date
